package com.pratikbhosale.daybook.data.local

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Instrumented test that exercises the real Room-generated SQL.
 *
 * Unlike the fake-based unit tests in [DatabaseSeederTest], this test:
 *   - Builds the actual [DaybookDatabase] with an in-memory Room instance
 *   - Uses the actual [BucketDao] generated by the Room annotation processor
 *   - Relies on the real UNIQUE index on `Bucket.name` to enforce INSERT OR IGNORE
 *
 * If the index is missing, misspelled, or [BucketDao.insertAll] lacks
 * [OnConflictStrategy.IGNORE], this test will fail with a count of 6, not 3.
 *
 * Must run on a device or emulator (instrumented test).
 * The in-memory database is destroyed after each test method.
 */
@RunWith(AndroidJUnit4::class)
class DatabaseSeederIntegrationTest {

    private lateinit var database: DaybookDatabase
    private lateinit var bucketDao: BucketDao

    @Before
    fun setUp() {
        database = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            DaybookDatabase::class.java,
        )
            // Allow main-thread queries only in tests — production code must never do this.
            .allowMainThreadQueries()
            .build()
        bucketDao = database.bucketDao()
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Test
    fun seedDefaultBuckets_firstCall_insertsThreeBuckets() = runTest {
        DatabaseSeeder.seedDefaultBuckets(bucketDao)

        assertEquals(
            "First seed must produce exactly 3 buckets",
            3,
            bucketDao.count(),
        )
    }

    @Test
    fun seedDefaultBuckets_calledTwice_rowCountStaysAtThree() = runTest {
        DatabaseSeeder.seedDefaultBuckets(bucketDao)
        DatabaseSeeder.seedDefaultBuckets(bucketDao) // must be a SQL-level no-op

        assertEquals(
            "Row count must stay at 3 after double seed — real UNIQUE index + INSERT OR IGNORE",
            3,
            bucketDao.count(),
        )
    }

    @Test
    fun seedDefaultBuckets_calledTwice_bucketNamesRemainUnique() = runTest {
        DatabaseSeeder.seedDefaultBuckets(bucketDao)
        DatabaseSeeder.seedDefaultBuckets(bucketDao)

        // Collect all names from the real DB; each must appear exactly once.
        val allBuckets = bucketDao.observeAll().first()

        val names = allBuckets.map { it.name }
        assertEquals(
            "No duplicate bucket names must exist in the real database after double seed",
            names.distinct().size,
            names.size,
        )
    }
}
